name: shell commands

on: [push]

jobs: 
  run-shell-command:
    runs-on: windows-latest
    steps:
      - name: echo a string
        run: eccho "Hello World"
      - name: multiline script
        run: | 
          node -v
          npm -v
# With that we run multiple commands
